### ISSUE TITLE
Translating into other languages

### ISSUE THREAD

**Issue by BluePixel4k** [DanielRendox/GroceryGenius#14]
Thanks for the nice app!

I would like to help to translate the app / grocery items into other language(s) (mainly German).
Is it already possible?

If you don't already have a service for it, then Weblate (open source) would be a good solution: https://weblate.org/en/
Codeberg.org (a non-profit organization) is hosting this service for free use: https://translate.codeberg.org/

And BTW: https://codeberg.org/ is generally a nice Git Hosting service (a good alternative to GitHub (Microsoft) :wink:)

**Comment by tubbadu** [comment]
I would also like to help in the translation to Italian!

**Comment by DanielRendox** [comment]
Hello! Sorry for the late response guys, supporting Grocery Genius isn't my priority right now. 🫤 

However, I've finally finished setting up the project's [Crowdin page](https://crowdin.com/project/grocery-genius). You can start by translating grocery item names in `default_products.json`, as it is the most important part, then move on to category names, app strings, and the remaining content.

Newly added translations will be available in the app's next release.
