### ISSUE TITLE
APK at v0.1.3 is signed using a debug key

### ISSUE THREAD

**Issue by IzzySoft** [DanielRendox/GroceryGenius#22]
Something went wrong with that release:

```
package: name='com.rendox.grocerygenius' versionCode='6' versionName='0.1.3' platformBuildVersionName='14' platformBuildVersionCode='34' compileSdkVersion='34' compileSdkVersionCodename='14'
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
Verified using v4 scheme (APK Signature Scheme v4): false
Verified for SourceStamp: false
Number of signers: 1
Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
Signer #1 certificate SHA-256 digest: d94c82682476f14ae99dd6e6630a634ef9450c63ca7cd8b558da3a5ec1e5c523
Signer #1 certificate SHA-1 digest: eccea0a8c3940ce69882456deba6753f96c523c5
Signer #1 certificate MD5 digest: 8c8b3e67e4e10d2e116adb3f29e5d977
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

Please use your release key to sign :wink: This APK was rejected by the updater at IzzyOnDroid.

**Comment by DanielRendox** [comment]
Oops... Updated with the correct signature

**Comment by IzzySoft** [comment]
That was fast – thanks! Reactivated daily updates.

Btw, having manually triggered that update I just notice

    ! repo/com.rendox.grocerygenius_6.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)

That can easily be avoided with a minor addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

PS: No RB shield for this release now unfortunately, as v0.1.3 was already committed to the builder logs and thus won't be processed again. Hashes of the APKs (debug/release key) will differ, hence the RB won't be found. Just in case you wonder.

**Comment by DanielRendox** [comment]
Yeah, you've already told me about the metadata. Thanks! Will be in the next release.
