### ISSUE TITLE
Translation into Italian 

### ISSUE THREAD

**Issue by stepersy** [DanielRendox/GroceryGenius#32]
Hello, I would like to help the development of the app by translating it in Italian. Does the project have any Crowdin or similar page?
Thank you, have a nice day!

**Comment by DanielRendox** [comment]
Hello! Thanks for your interest in helping with translations! I finally had some free time to finish setting up the project's [Crowdin page](https://crowdin.com/project/grocery-genius). You can start by translating grocery item names in `default_products.json`, as it is the most important part, then move on to category names, app strings, and the remaining content.

Newly added translations will be available in the app's next release.
